config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'movies#index'

  resources :movies do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/concerns/link_validator.rb
require 'addressable/uri'

class LinkValidator < ActiveModel::Validator
  def validate(record)
    return if record.link.blank?
    uri = parsed_uri(record.link)

    if unaccepted_protocols(uri.scheme) ||
       unaccepted_domains(uri.host)
      fail Addressable::URI::InvalidURIError
    end
  rescue Addressable::URI::InvalidURIError
    record.errors.add(:link, 'must be a valid IMDB link!')
  end

  private

  def parsed_uri(value)
    Addressable::URI.parse(value)
  end

  def unaccepted_protocols(scheme)
    !%w(http https).include?(scheme)
  end

  def unaccepted_domains(host)
    # m.imdb.com for mobile
    !['www.imdb.com', 'm.imdb.com', 'imdb.com'].include?(host)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :movies, through: :categorizations

  validates :title, presence: true,
                    length: { in: 1..60 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  include PgSearch
  pg_search_scope :search,
                  against: {
                    title: 'A',
                    storyline: 'B'
                  },
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }

  has_many :categorizations, dependent: :destroy
  has_many :genres, through: :categorizations

  validates :title, presence: { message: 'must be included!' },
                    length: { in: 1..100, message: 'must be between 1 and 100 characters!' }
  validates :storyline, length: { maximum: 1000, message: 'must be under 1000 characters!' }
  validates_with LinkValidator
end

app/models/suggested_movie.rb
class SuggestedMovie
  def self.all
    Movie.order(created_at: :desc).limit(5)
  end
end

app/models/suggested_movies.rb
class SuggestedMovies
  def self.all
    Movie.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :show]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      flash.now[:error] = @movie.errors.full_messages
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      flash.now[:error] = @movie.errors.full_messages
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path
    else
      render :show
    end
  end

  def search
    @movies = Movie.search(params[:query])
    if @movies.any?
      render :search
    else
      @suggested_movies = SuggestedMovie.all
      render :suggested
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :storyline, :release, :link, genre_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def manage_sessions
    if user_signed_in?
      link_to 'Log Out', destroy_user_session_path, method: :delete
    else
      link_to 'Log In', new_user_session_path
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def display_release_date(release)
    if release
      release.strftime('%b %d, %Y')
    else
      'no date given'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sproof</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render "shared/flash" %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/movies/_genre_tags.html.erb
<% genres.each do |genre| %>
  <span class="label label-default"><%= genre.title %></span>
<% end %>

app/views/movies/_movie.html.erb
<%= link_to movie_path(movie), class: "list-group-item" do %>
  <h5 class="list-group-item-heading">
    <%= movie.title %>
  </h5>
  <p class="list-group-item-text">
  <%= truncate(movie.storyline, length: 140) %>
  </p>
  <%= render partial: 'genre_tags', locals: { genres: movie.genres } %>
<% end %>

app/views/movies/_movie_form.html.erb
<div class="form">
  <%= form_for movie, :html => {:class => "form-horizontal"} do |m| %>
    <fieldset>
      <div class="form-group">
        <%= m.label :title, class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= m.text_field :title, class: 'form-control' %>
        </div>
      </div>


      <div class="form-group">
        <%= m.label :storyline, class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= m.text_area :storyline, class: 'form-control'  %>
        </div>
      </div>


      <div class="form-group">
        <%= m.label :release, class: 'col-lg-2 control-label'%>
        <div class="col-lg-10">
          <%= m.date_select :release, { :start_year => Date.current.year, :end_year => 1900 }, { class: 'form-control date-select'} %>
        </div>
      </div>


      <div class="form-group">
        <%= m.label :genre , class: 'col-lg-2 control-label'%>
        <div class="col-lg-10">
          <%= m.collection_check_boxes(:genre_ids, Genre.all, :id, :title) do |c| %>
            <div class='form-check'>
              <%= c.label class: 'form-check-label' do %>
                <%= c.check_box class: 'form-check-input' %>
                <%= c.text %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group">
        <%= m.label :link, class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= m.text_field :link, class: 'form-control' %>
          <span class="help-block">
            Only official IMDB links are accepted. <br>
            Ex: <i>http://www.imdb.com/title/tt0092048/</i>
          </span>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <%= m.submit "Submit", class: 'btn btn-default' %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/movies/edit.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h4 class="text-center"><b>Update Movie</b></h4>
  <hr>
  <%= render partial: "movie_form", locals: { movie: @movie } %>
</div>

app/views/movies/index.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <div class="list-group">
    <% @movies.each do |movie| %>
      <%= render partial: "movie", locals: { movie: movie } %>
    <% end %>
  </div>

  <%= link_to "Add movie", new_movie_path, class: "btn btn-success btn-block btn-lg" %>
</div>

app/views/movies/new.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h4 class="text-center"><b>Add Movie</b></h4>
  <hr>
  <%= render partial: "movie_form", locals: { movie: @movie } %>
</div>

app/views/movies/search.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3 class="text-left"><b><%= pluralize( @movies.length, 'Search Result') %></b></h3>

  <% @movies.each do |movie| %>
    <%= render partial: "movie", locals: { movie: movie } %>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="col-sm-offset-3 col-sm-6">
  <h3 class="text-center"><b><%= @movie.title %></b></h3>
  <dl>
    <dt>Release Date</dt>
    <dd><%= display_release_date(@movie.release) %></dd>
    <dt>Storyline</dt>
    <dd><%= @movie.storyline %></dd>
    <%= render partial: 'genre_tags', locals: { genres: @movie.genres } %>
  </dl>

  <div class="btn-group btn-group-justified">
    <%= link_to "Edit movie", edit_movie_path(@movie), class: "btn btn-default btn-sm" %>
    <a href="<%= @movie.link %>" class="btn btn-default btn-sm">IMDB</a>
    <%= link_to "Delete movie", movie_path(@movie), method: :delete, class: "btn btn-default btn-sm" %>
  </div>
  <br><br>
  <ul class="pager">
    <li>
    <%= link_to "<< All movies", movies_path, class: "text-center" %>
    </li>
  </ul>
</div>

app/views/movies/suggested.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3 class="text-left"><b>Sorry, your search didn't return any results.</b></h3>
  <hr>
  <br>
  <h5 class="text-center">Check out some of our latest movies instead!</h5>
  <br>
  <% @suggested_movies.each do |movie| %>
    <%= render partial: "movie", locals: { movie: movie } %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning">
    <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
    &nbsp;
    <% Array(value).each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <b>
        <%= link_to root_path, class: "navbar-brand" do %>
          SPROOF
          <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
        <% end %>
      </b>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "All Movies", root_path %></li>
            <li><%= link_to "Add Movie", new_movie_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= manage_sessions %></li>
      </ul>
      <%= render "shared/search_form" %> 
    </div>
  </div>
</nav>

app/views/shared/_search_form.html.erb
<div class="form-group navbar-form navbar-right">
  <%= form_tag search_movies_path, method: 'get' do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Search movies...', class: 'form-control' %>
    <%= button_tag(type: 'submit', class: "btn btn-default") do %>
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    <% end %>
  <% end %>
</div>